Added create-palette script; allow palette to be passed in instead of just a list of colors

diff --git a/extract-svgs b/extract-svgs
--- a/extract-svgs
+++ b/extract-svgs
@@ -1,7 +1,7 @@
 #!/bin/zsh
 
 # TODO: Specify the colors you want to conform to using a palette
-#       This would allow user to specify the filament colors that can be made and map the image
+#       This would allow user to specify the filament colors that can be made and palette the image
 #       to those colors.
 #       See (instead of -colors) https://imagemagick.org/script/command-line-options.php#remap
 #           # Create a palette with one color per pixel for the colors you want to use
@@ -17,10 +17,10 @@ function usage() {
     echo "It also adds a small rectangle in two corners of the image to help with alignment and sizing."
     echo
     echo "Usage:"
-    echo "  $0 <input_image> <output_location> <color_count> [--rect-size|-s <rect_size>] [--alignment-corners|-c (tl|tr|bl|br|none)] [--help] [--no-confirm|-n] [--delete-output|-d]"
+    echo "  $0 <input_image> <output_location> [--color-count <color_count>] [--rect-size|-s <rect_size>] [--alignment-corners|-a (tl|tr|bl|br|none)] [--help] [--no-confirm|-n] [--delete-output|-d] [--palette|-p <palette_file>]"
     echo
     echo "Options:"
-    echo "  -c (tlbr|trbl|none), --rect-corners <corners>   Set the corners of the rectangle (default: tlbr)"
+    echo "  -a (tlbr|trbl|none), --rect-corners <corners>   Set the corners of the rectangle (default: tlbr)"
     echo "                                                  Acceptable values:"
     echo "                                                  * tlbr: Top Left, Bottom Right"
     echo "                                                  * trbl: Top Right, Bottom Left"
@@ -30,8 +30,10 @@ function usage() {
     echo "                                                  * right: Top Right, Bottom Right"
     echo "                                                  * all: All corners"
     echo "                                                  * none: No alignment squares"
+    echo "  -c, --color-count <color_count>                 Set the number of colors to extract (default: 16)"
     echo "  -d, --delete-output                             Delete the output files after processing"
     echo "  --help                                          Show this help message"
+    echo "  -p <palette_file>, --palette <palette_file>     Use a color palette file to limit the colors"
     echo "  -n, --no-confirm                                Skip confirmation before processing"
     echo "  -s <rect_size>, --rect-size <rect_size>         Set the size of the rectangle (default: 100)"
     echo
@@ -39,29 +41,30 @@ function usage() {
     exit 1
 }
 
+#region Input and Validation
+
 # Parse the input arguments
-if [ $# -lt 3 ]; then
+if [ $# -lt 2 ]; then
     usage
 fi
 
 # Assign arguments to variables
 INPUT_IMAGE=$1
 OUTPUT_LOCATION=$2
-COLOR_COUNT=$3
 
 # Set values for arguments
 RECT_SIZE=100
 NO_CONFIRM=false
 
 # Parse optional arguments
-shift 3
+shift 2
 while [[ $# -gt 0 ]]; do
     case $1 in
         -s|--rect-size)
             RECT_SIZE=$2
             shift 2
             ;;
-        -c|--alignment-corners)
+        -a|--alignment-corners)
             local CORNER=$2:l
             if typeset -p bob 2>/dev/null | grep -q "\-a" ; then
                 ALIGN_CORNERS=()
@@ -83,6 +86,10 @@ while [[ $# -gt 0 ]]; do
             fi
             shift 2
             ;;
+        -c|--color-count)
+            COLOR_COUNT=$2
+            shift 2
+            ;;
         -d|--delete-output)
             DELETE_OUTPUT=true
             shift
@@ -95,6 +102,10 @@ while [[ $# -gt 0 ]]; do
             usage
             exit 0
             ;;
+        -p|--palette)
+            PALETTE_FILE=$2
+            shift 2
+            ;;
         *)
             echo "Unknown option: $1"
             usage
@@ -102,6 +113,17 @@ while [[ $# -gt 0 ]]; do
             ;;
     esac
 done
+
+# Check that only --palette or --colors is used, not both
+if [[ -n "$PALETTE_FILE" && -n "$COLOR_COUNT" ]]; then
+    echo "You cannot specify both --palette and --colors at the same time."
+    exit 1
+fi
+
+# If no --palette or --colors is specified, set the default to 16
+if [[ -z "$PALETTE_FILE" && -z "$COLOR_COUNT" ]]; then
+    COLOR_COUNT=16
+fi
 
 # Check if corners contain none and anything else
 if [[ "$ALIGN_CORNERS" == *"none"* && "${#ALIGN_CORNERS[@]}" -gt 1 ]]; then
@@ -172,6 +194,12 @@ if [[ -e "$OUTPUT_LOCATION" ]]; then
     fi
 fi
 
+#Check that the palette file exists
+if [[ -n "$PALETTE_FILE" && ! -f "$PALETTE_FILE" ]]; then
+    echo "palette file not found!"
+    exit 1
+fi
+
 # Create the output directory if it doesn't exist
 mkdir -p "$OUTPUT_LOCATION"
 OUTPUT_LOCATION=$(realpath "$OUTPUT_LOCATION")
@@ -181,16 +209,21 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 # Check if the color count is a valid number
-if ! [[ "$COLOR_COUNT" =~ ^[0-9]+$ ]]; then
+if [[ -n "$COLOR_COUNT" && ! "$COLOR_COUNT" =~ ^[0-9]+$ ]]; then
     echo "Color count must be a valid number!"
     exit 1
 fi
 # Check if the color count is within a reasonable range
-if [ "$COLOR_COUNT" -lt 1 ] || [ "$COLOR_COUNT" -gt 256 ]; then
-    echo "Color count must be between 1 and 256!"
-    exit 1
+if [ -n "$COLOR_COUNT" ]; then
+    if [ [ "$COLOR_COUNT" -lt 1 ] || [ "$COLOR_COUNT" -gt 256 ] ]; then
+        echo "Color count must be between 1 and 256!"
+        exit 1
+    fi
 fi
 
+#endregion
+
+#region Functions
 
 # Function to display a hex color with contrasting text in the terminal
 function display_hex_color() {
@@ -245,17 +278,41 @@ function svg_has_drawable_elements() {
   fi
 }
 
-COLOR_IMAGE="$OUTPUT_LOCATION/color_$COLOR_COUNT.png"
+#endregion
+
 echo
-# Convert the image to an x-color version of the image
-echo -n "Converting image to $COLOR_COUNT colors..."
-magick "$INPUT_IMAGE" -fuzz 20% -colors $COLOR_COUNT -depth 8 "$COLOR_IMAGE"
-# Check if the conversion was successful
-if [ $? -ne 0 ]; then
-    echo "Image conversion failed!"
-    exit 1
+
+# If a palette file is specified, use it to limit the colors
+if [[ -n "$PALETTE_FILE" ]]; then
+    COLOR_IMAGE="$OUTPUT_LOCATION/color_mapped.png"
+    FILE_SUBEXT="mapped"
+
+    # Convert the image to an x-color version of the image
+    echo -n "Converting image using palette file ($PALETTE_FILE)..."
+    magick "$INPUT_IMAGE" -remap "$PALETTE_FILE" "$COLOR_IMAGE"
+    # Check if the conversion was successful
+    if [ $? -ne 0 ]; then
+        echo "Image conversion failed!"
+        exit 1
+    fi
+    echo "done"
 fi
-echo "done"
+
+# If color_count is provided, convert the image to that many colors
+if [[ -n "$COLOR_COUNT" ]]; then
+    COLOR_IMAGE="$OUTPUT_LOCATION/color_$COLOR_COUNT.png"
+    FILE_SUBEXT="$COLOR_COUNT"
+
+    # Convert the image to an x-color version of the image
+    echo -n "Converting image to $COLOR_COUNT colors..."
+    magick "$INPUT_IMAGE" -fuzz 20% -colors $COLOR_COUNT -depth 8 "$COLOR_IMAGE"
+    # Check if the conversion was successful
+    if [ $? -ne 0 ]; then
+        echo "Image conversion failed!"
+        exit 1
+    fi
+    echo "done"
+fi
 
 COLOR_ARRAY=()
 # Get the colors from the image
@@ -301,7 +358,7 @@ else
 fi
 
 # Extract the alpha channel from the image
-ALPHA_IMAGE="$OUTPUT_LOCATION/transparent_$COLOR_COUNT.png"
+ALPHA_IMAGE="$OUTPUT_LOCATION/transparent_$FILE_SUBEXT.png"
 magick "$COLOR_IMAGE" -alpha extract "$ALPHA_IMAGE"
 # Check if the alpha extraction was successful
 if [ $? -ne 0 ]; then
@@ -322,8 +379,8 @@ INDEX=1
 # Loop through the colors
 for COLOR in "${COLOR_ARRAY[@]}"; do
     FILECOLOR=$(echo ${COLOR:0:7} | sed 's/#//g')
-    TEMP_FILENAME="$OUTPUT_LOCATION/temp_$FILECOLOR.$COLOR_COUNT.png"
-    OUTPUT_FILENAME_BASE="$OUTPUT_LOCATION/$FILECOLOR.$COLOR_COUNT.layer"
+    TEMP_FILENAME="$OUTPUT_LOCATION/temp_$FILECOLOR.$FILE_SUBEXT.png"
+    OUTPUT_FILENAME_BASE="$OUTPUT_LOCATION/$FILECOLOR.$FILE_SUBEXT.layer"
     OUTPUT_FILENAME_SVG="$OUTPUT_FILENAME_BASE.svg"
     OUTPUT_FILENAME_PNG="$OUTPUT_FILENAME_BASE.png"
     
@@ -418,7 +475,7 @@ for COLOR in "${COLOR_ARRAY[@]}"; do
         echo "done"
     else
         # echo "SVG has no drawable elements. Skipping $OUTPUT_FILENAME_SVG"
-        rm "$OUTPUT_FILENAME_SVG"
+        # rm "$OUTPUT_FILENAME_SVG"
         echo "done (skipped)"
     fi
 
